-- 코드를 입력하세요
SELECT ANIMAL_ID, NAME, SEX_UPON_INTAKE
FROM ANIMAL_INS
WHERE NAME LIKE "Lucy" || NAME LIKE "Ella" || NAME LIKE "Pickle" || NAME LIKE "Rogan" || NAME LIKE "Sabrina" || NAME LIKE "Mitty"
ORDER BY ANIMAL_ID;